# Generated by Django 4.2 on 2025-04-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], max_length=20, verbose_name='Состояние товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображение'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
    ]
