# Generated by Django 4.2 on 2025-04-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_category_alter_ad_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('smartphones', 'Смартфоны'), ('laptops', 'Ноутбуки'), ('clothing', 'Одежда'), ('shoes', 'Обувь'), ('books', 'Книги'), ('furniture', 'Мебель'), ('appliances', 'Бытовая техника'), ('sports', 'Спорт и отдых'), ('toys', 'Игрушки'), ('tools', 'Инструменты'), ('vehicles', 'Транспорт'), ('bicycles', 'Велосипеды'), ('jewelry', 'Ювелирные изделия'), ('art', 'Искусство'), ('music', 'Музыкальные инструменты'), ('pets', 'Животные'), ('gardening', 'Садоводство'), ('other', 'Другое')], verbose_name='Категория', max_length=20),
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad')),
            ],
        ),
    ]
