# Generated by Django 4.2 on 2025-04-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_category_exchangeproposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeproposal',
            old_name='comments',
            new_name='comment',
        ),
    ]
